name: Build and Deploy to dockerhub

on:
  push:
    branches:
      - main
jobs:
  Continuous-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: yshplsngh/testimonial:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker rmi yshplsngh/testimonial:latest --force || true
            sudo docker compose up -d
            
          
